apiVersion: apps/v1
kind: Deployment
metadata:
  name: selfupdateagent
  labels:
    app: selfupdateagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selfupdateagent
  template:
    metadata:
      labels:
        app: selfupdateagent
    spec:
      containers:
        - name: selfupdateagent
          image: ghcr.io/eclipse-leda/sdv-self-update-agent/sua:v0.1.16
          imagePullPolicy: IfNotPresent 
# Commented out for big memory limits
#          resources:
#            requests:
#              cpu: "50m"
#            limits:
#              memory: "128Mi"
#              cpu: "500m"
          volumeMounts:                                                      
          - mountPath: /var/run/dbus/system_bus_socket                       
            name: system-dbus-socket                                         
            readOnly: true                                                   
          - mountPath: /RaucUpdate
            name: shared-rauc-vol 
          ports:
          - name: default
            containerPort: 50052
            protocol: TCP
      imagePullSecrets:
      - name: ghcr-io
      volumes:                                                                            
      - hostPath:                                                                         
          path: /var/run/dbus/system_bus_socket                            
        name: system-dbus-socket                                           
      - hostPath:                                                          
          path: /data/selfupdates
        name: shared-rauc-vol 
---
apiVersion: v1
kind: Service
metadata:
  name: selfupdateagent-nodeport
spec:
  type: NodePort
  selector:
    app: selfupdateagent
  ports:
    - port: 50052
      targetPort: 50052
      nodePort: 30052
