#!/bin/sh
# shellcheck disable=SC3043
# shellcheck disable=SC1091
# shellcheck disable=SC2086
# shellcheck disable=SC2034
# shellcheck disable=SC2059
# /********************************************************************************
# * Copyright (c) 2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

tar_dir=$1

if [ -z "${tar_dir}" ]; then
    echo "Using current working directory as image directory"
    tar_dir=$(pwd)
fi

if [ ! -d "${tar_dir}" ]; then
    echo "${tar_dir} either does not exist or is not a directory"
    exit 1
fi 

if [ -z "$(ls -A ${tar_dir}/*.tar* 2>/dev/null)" ]; then
   echo "Nothing to install"
   exit 0
fi

for tar_image in "${tar_dir}"/*.tar*; do
    ctr --namespace kanto-cm image import ${tar_image} --no-unpack
done
