# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/
# Every file needs to contain a header, that provides kas with information
# about the context of this file.
header:
  # The `version` entry in the header describes for which configuration
  # format version this file was created for. It is used by kas to figure
  # out if it is compatible with this file. The version is an integer that
  # is increased on every format change.
  version: 12
# The machine as it is written into the `local.conf` of bitbake.
machine: qemux86-64
# The distro name as it is written into the `local.conf` of bitbake.
distro: leda
target: sdv-image-all
local_conf_header:
  meta-leda: |
    INHERIT:append = " rm_work"
    INHERIT:remove = " archiver"
    INHERIT:remove = " cve-check"
    INHIBIT_PACKAGE_DEBUG_SPLIT = "1"
repos:
  # This entry includes the repository where the config file is located
  # to the bblayers.conf:
  # Here we include a list of layers from the poky repository to the
  # bblayers.conf:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    refspec: honister
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
  meta-rauc-community:
    url: "https://github.com/rauc/meta-rauc-community.git"
    refspec: master
    layers:
      meta-rauc-qemux86:
  meta-rauc:
    url: "https://github.com/rauc/meta-rauc.git"
    refspec: honister
  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    refspec: honister
  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    refspec: honister
    layers:
      meta-oe:
      meta-filesystems:
      meta-python:
      meta-networking:
  meta-leda:
    path: ./
    layers:
      meta-leda-bsp:
      meta-leda-components:
      meta-leda-distro:
