apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudagent
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cloudagent
  template:
    metadata:
      labels:
        component: cloudagent
    spec:
      containers:
        - name: cloudagent
          image: ghcr.io/softwaredefinedvehicle/swdc-os-cloud-agent/cloudagent:v0.3
          resources:
            requests:
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: cloudagent
                  key: PrimaryConnectionString
                  optional: false
            - name: LOCAL_ADDRESS
              value: tcp://mosquitto:1883
            - name: LOG_FILE
              value: ""
            - name: CA_CERT_PATH
              value: "/app/iothub.crt"
            - name: MESSAGE_MAPPER_CONFIG
              value: "/app/message-mapper-config.json"
            - name: ALLOWED_CLOUD_MESSAGE_TYPES_LIST
              value: "vss.setPosition,updateme,subscribeOnceCommand,vss.set"
            - name: ALLOWED_LOCAL_TOPICS_LIST
              value: "cloudConnector/#"          
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: ghcr-io
