apiVersion: v1
kind: Pod
metadata:
  name: sdv-core-cloud-agent-pod
spec:
  restartPolicy: Always
  hostAliases:
  - ip: "10.0.2.15"
    hostnames:
    - "edgehost"
  containers:
    - name: cloudagent
      image: ghcr.io/softwaredefinedvehicle/swdc-os-cloud-agent/cloudagent:v0.1
      env:
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: cloudagent
              key: PrimaryConnectionString
              optional: false
        - name: LOCAL_ADDRESS
          value: tcp://edgehost:1883
        - name: LOG_FILE
          value: ""
        - name: CA_CERT_PATH
          value: "/app/iothub.crt"
        - name: MESSAGE_MAPPER_CONFIG
          value: "/app/message-mapper-config.json"
      imagePullPolicy: IfNotPresent
  imagePullSecrets:
  - name: ghcr-io