apiVersion: v1
kind: Pod
metadata:
  name: sdv-core-cloud-agent-pod
spec:
  restartPolicy: Always
  hostAliases:
  - ip: "10.42.0.1"
    hostnames:
    - "edgehost"
  containers:
    - name: cloudagent
      image: ghcr.io/softwaredefinedvehicle/swdc-os-cloud-agent/cloud-agent:v0.0.1
      imagePullPolicy: IfNotPresent
