apiVersion: v1
kind: Pod
metadata:
  name: sdv-core-cloud-agent-pod
spec:
  restartPolicy: Always
  containers:
    - name: cloudagent
      image: ghcr.io/softwaredefinedvehicle/swdc-os-cloud-agent/cloudagent:v0.2
      env:
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: cloudagent
              key: PrimaryConnectionString
              optional: false
        - name: LOCAL_ADDRESS
          value: tcp://mosquitto:1883
        - name: LOG_FILE
          value: ""
        - name: CA_CERT_PATH
          value: "/app/iothub.crt"
        - name: MESSAGE_MAPPER_CONFIG
          value: "/app/message-mapper-config.json"
        - name: ALLOWED_CLOUD_MESSAGE_TYPES_LIST
          value: "vss.setPosition,updateme,subscribeOnceCommand,vss.set"
      imagePullPolicy: IfNotPresent
  imagePullSecrets:
  - name: ghcr-io