apiVersion: v1
kind: Deployment
metadata:
  name: vehicle-update-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      component: vehicle-update-manager
  template:
    metadata:
      labels:
        component: vehicle-update-manager
    spec:
      containers:
        - name: vehicle-update-manager
          image: ghcr.io/softwaredefinedvehicle/swdc-os-containers-management/vehicleupdatemanager:v0.4
          imagePullPolicy: IfNotPresent
          env:
          - name: THINGS_CONN_BROKER
            value: tcp://mosquitto:1883
          - name: THINGS_FEATURES
            value: ContainerOrchestrator 
      imagePullSecrets:
      - name: ghcr-io
