apiVersion: v1
kind: Pod
metadata:
  name: sdv-edge-update-manager
spec:
  restartPolicy: Always
  hostAliases:
  - ip: "10.0.2.15"
    hostnames:
    - "edgehost"
  containers:
    - name: edge-update-manager
      image: ghcr.io/softwaredefinedvehicle/swdc-edge-update-manager/update-manager:v0.0.1
      imagePullPolicy: IfNotPresent
  imagePullSecrets:
  - name: azurecr