name: Build Poky with SDV Core

on:
  workflow_dispatch:
  workflow_call:

jobs:

  poky-core-qemux86_64:
    name: "poky-minimal-sdv-core-qemux86_64"
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends socat file gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint xterm python3-subunit mesa-common-dev zstd liblz4-tool tmux mc skopeo fdisk ruby-full jq libvirt-clients libvirt-daemon-system qemu-system-x86 qemu-system-arm qemu-kvm squashfs-tools rauc python3-newt ca-certificates curl gnupg lsb-release
    
    - name: Install kas
      run: sudo pip3 install kas

    - name: Build poky-core-image-minimal + sdv-core
      env:
        KAS_MACHINE: qemux86-64
      run: |
        (r=3;while ! kas build kas/poky-sdv-qemux86-64.yaml; do ((--r))||exit;sleep 60;done)

    - name: Package all files
      run: |
        export ARC=poky-minimal-sdv-core-qemu-x86_64.tar
        rm -f ${ARC}.xz
        time tar --append --verbose --dereference --file ${ARC} -C ./build/tmp/deploy/images/qemux86-64/ \
          bzImage-qemux86-64.bin \
          core-image-minimal-qemux86-64.ext4 \
          core-image-minimal-qemux86-64.manifest \
          core-image-minimal-qemux86-64.qemuboot.conf \
          core-image-minimal-qemux86-64.tar.bz2 \
          core-image-minimal-qemux86-64.testdata.json \
          modules-qemux86-64.tgz
        time xz -v -8 -T0 ${ARC}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: poky-minimal-sdv-core-qemu-x86_64.tar.xz
        if-no-files-found: error
        path: poky-minimal-sdv-core-qemu-x86_64.tar.xz